Fix: ``on_success_callback`` will no longer execute if a task is skipped. Previously, this callback was triggered even when the task was skipped.
